[versions]
project = "1.0.0"
kotlin = "1.8.0"
gson = "2.10.1"
shadowJar = "7.1.2"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadowJar = { id = "com.github.johnrengelman.shadow", version.ref = "shadowJar" }
