[versions]
kotlin = "1.8.0"
gson = "2.10.1"
mockk = "1.13.5"
koin = "3.4.0"
testLogger = "3.2.0"

[libraries]
koin = { module = "io.insert-koin:koin-core", version.ref = "koin" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
testLogger = { id = "com.adarshr.test-logger", version.ref = "testLogger" }
